name: Run Shell Tests in Specific Folder

on:
  push:
    paths:
      - 'Modules/Module00/ex02/tests/script.sh'

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Compile main.cpp
      run: |
        cd Modules/Module00/ex02
        g++ -o tests/program main.cpp
      
    - name: Run tests
      run: |
        cd Modules/Module00/ex02/tests
        bash script.sh
