name: Run Shell Tests in Specific Folder

on:
  push:
    paths:
      - 'Modules/Module01/ex02'

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Compile executable
      run: |
        cd Modules/Module01/ex02
        make

    - name: Run tests
      run: |
        make test
