name: Module Tests

on:
  push:
    # Uncomment and define paths if needed, like:
    # paths:
    #   - 'Module01/ex00/**'
    #   - 'Module01/ex01/**'
    #   - 'Module01/ex02/**'
  pull_request:
    # Uncomment and define paths if needed, like:
    # paths:
    #   - 'Module01/ex00/**'
    #   - 'Module01/ex01/**'
    #   - 'Module01/ex02/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - 'Module01/ex00'
          - 'Module01/ex01'
          - 'Module01/ex02'

    steps:
    - uses: actions/checkout@v2

    #- name: Setup compiler and tools
      #run: |
        #sudo apt-get update
        #sudo apt-get install -y g++ make valgrind

    - name: Check Makefile exists in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}  # Navigate to the correct folder
        if [ ! -f "Makefile" ]; then
          echo "::error::Makefile not found in ${{ matrix.folder }}"
          exit 1
        fi

    - name: Compile in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}  # Navigate to the correct folder
        make
        if [ ! -f "./program" ]; then
          echo "::error::Executable 'program' not created"
          exit 1
        fi

    - name: Run tests in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}  # Navigate to the correct folder
        if [ -f "./test.sh" ]; then
          chmod +x ./test.sh
          ./test.sh
        else
          echo "Running executable directly..."
          ./program
        fi

    - name: Check memory leaks in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}  # Navigate to the correct folder
        valgrind --leak-check=full \
                 --show-leak-kinds=all \
                 --track-origins=yes \
                 --verbose \
                 --error-exitcode=1 \
                 ./program

    - name: Clean in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}  # Navigate to the correct folder
        make fclean
