name: Run Action on Folder Change

on:
  push:
    paths:
      - 'Module01/ex00/**'
      - 'Module01/ex01/**'
      - 'Module01/ex02/**'
  pull_request:
    paths:
      - 'Module01/ex00/**'
      - 'Module01/ex01/**'
      - 'Module01/ex02/**'

jobs:
  check-modified-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List changed files
      run: |
        echo "Changed files:"
        git diff --name-only ${{ github.event.before }} ${{ github.event.after }}  # Show files modified in push/pull request

    - name: Run action if files in the folder are modified
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})

        if echo "$CHANGED_FILES" | grep -q '^Module01/ex02/'; then
          echo "Files inside 'Module01/ex02/' have been modified. Running action..."
          # Put your custom action/command here, for example:
          # ./your-script.sh
        else
          echo "No files in 'Module01/ex02/' have been modified. Skipping action."
        fi
