name: Module 03

on:
  push:
    paths:
      - 'Modules/Module03/**'
  pull_request:
    paths:
      - 'Modules/Module03/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        dir: '${{github.workspace}}/qt/'
        modules: 'qtcharts qtwebengine qtwebchannel qtwebsockets'

    - name: Create Build Directory
      run: mkdir build

    - name: Configure CMake
      working-directory: ${{github.workspace}}/build
      run: cmake ..

    - name: Build
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Releasthi

    - name: Package Application
      working-directory: ${{github.workspace}}/build
      run: |
        mkdir package
        cp YourApp package/
        # Add any additional files needed for distribution

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: qt-app
        path: build/package/
