name: Module Tests

on:
  push:
    # Uncomment and define paths if needed, like:
    # paths:
    #   - 'Module01/ex00/**'
    #   - 'Module01/ex01/**'
    #   - 'Module01/ex02/**'
  pull_request:
    # Uncomment and define paths if needed, like:
    # paths:
    #   - 'Module01/ex00/**'
    #   - 'Module01/ex01/**'
    #   - 'Module01/ex02/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - 'Modules/Module01/ex00'
          - 'Modules/Module01/ex01'
          - 'Modules/Module01/ex02'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    #- name: Setup compiler and tools
      #run: |
        #sudo apt-get update
        #sudo apt-get install -y g++ make valgrind

    - name: Check Makefile exists in ${{ matrix.folder }}
      run: |
        echo "Checking if Makefile exists in ${matrix.folder}"
        cd ${{ matrix.folder }}
        ls -l  # Debug: list contents of the folder to verify if Makefile is there
        if [ ! -f "Makefile" ]; then
          echo "::error::Makefile not found in ${{ matrix.folder }}"
          exit 1
        fi

    - name: Compile in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}
        make
        if [ ! -f "./main" ]; then
          echo "::error::Executable 'main' not created"
          exit 1
        fi

    - name: Run tests in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}
        if [ -f "./script.sh" ]; then
          chmod +x ./script.sh
          ./script.sh
        else
          echo "Running executable directly..."
          ./main
        fi

    - name: Check memory leaks in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}
        valgrind --leak-check=full \
                 --show-leak-kinds=all \
                 --track-origins=yes \
                 --verbose \
                 --error-exitcode=1 \
                 ./main

    - name: Clean in ${{ matrix.folder }}
      run: |
        cd ${{ matrix.folder }}
        make fclean
