name: Module 03

on:
  push:
    paths:
      - 'Modules/Module03/**'
  pull_request:
    paths:
      - 'Modules/Module03/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.8.0'
        host: 'linux'
        target: 'desktop'
        arch: 'gcc_64'
        dir: '${{github.workspace}}/qt'
        modules: 'qtcharts qtwidgets'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build cmake libgl1-mesa-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: |
        cmake .. \
          -DCMAKE_PREFIX_PATH=${{github.workspace}}/qt/Qt/6.8.0/gcc_64 \
          -DCMAKE_BUILD_TYPE=Release

    - name: Build
      working-directory: build
      run: cmake --build . --config Release

    # Optional: Run tests if you have them
    #- name: Test
    #  working-directory: build
    #  run: ctest --output-on-failure
