name: Run Shell Tests in Specific Folder

on:
  push:
    paths:
      - 'Modules/Module01/ex00'

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Compile main.cpp
      run: |
        cd Modules/Module01/ex00/srcs
        g++ -o tests/program main.cpp Car.cpp

    - name: Run tests
      run: |
        cd Modules/Module01/ex00/tests
        bash script.sh
