name: Running tests for M00 EX03

on:
  push:
    paths:
      - './Modules/Module00/ex03'

jobs:
  test:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v3

    - name: Compile executable
      run: |
        cd Modules/Module00/ex03
        make
      
    - name: Run tests
      run: |
        make test
