name: Module 00 Tests

on:
  push:
  # paths:
    #   - 'Module00/ex02/**'
    #   - 'Module00/ex03/**'
  pull_request:
  # paths:
    #   - 'Module00/ex02/**'
    #   - 'Module00/ex03/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - 'Modules/Module00/ex02'
          - 'Modules/Module00/ex03'
    steps:
    - uses: actions/checkout@v3

    - name: Compile executable
      run: |
        cd ${{ matrix.folder }}
        make

    - name: Run tests
      run: |
        cd ${{ matrix.folder }}
        make test
