name: Running tests for M01 EX01

on:
  push:
    paths:
      - 'Modules/Module01/ex01/**'

jobs:
  test:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Compile executable
      run: |
        cd Modules/Module01/ex01
        make

    - name: Run tests
      run: |
        pwd
        ls -la
        make test
