name: Module 01

on:
  push:
    paths:
      - 'Modules/Module01/**'
  pull_request:
    paths:
      - 'Modules/Module01/**'
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder:
          - 'Modules/Module01/ex00'
          - 'Modules/Module01/ex01'
          - 'Modules/Module01/ex02'
    steps:
    - uses: actions/checkout@v3

    - name: Compile executable
      run: |
        cd ${{ matrix.folder }}
        make

    - name: Run tests
      run: |
        cd ${{ matrix.folder }}
        make test
