name: Module 01 Tests

on:
  push:

  pull_request:

jobs:
  build-and-test:
    runs-on: self-hosted

    strategy:
      matrix:
        folder:
          - 'Modules/Module01/ex00'
          - 'Modules/Module01/ex01'
          - 'Modules/Module01/ex02'
    steps:
    - uses: actions/checkout@v3

    - name: Compile executable
      run: |
        cd ${{ matrix.folder }}
        make

    - name: Run tests
      run: |
        cd ${{ matrix.folder }}
        make test
