name: Test Workflow for GitHub Actions Branch

on:
  push:
    branches:
      - github-actions  # Trigger only on pushes to the github-actions branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print a message
        run: echo "This is a test action to confirm triggers on the github-actions branch."
